# Generated by Django 3.2.8 on 2021-12-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11',
            name='max_critical_tem',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='max_severe_tem',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='min_critical_tem',
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='min_severe_tem',
        ),
        migrations.CreateModel(
            name='Telemtry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_critical_tem', models.FloatField(null=True)),
                ('max_severe_tem', models.FloatField(null=True)),
                ('max_critical_tem', models.FloatField(null=True)),
                ('min_severe_tem', models.FloatField(null=True)),
                ('dht11', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemtries', to='myapp.dht11', verbose_name='Dht11')),
            ],
        ),
    ]
