# Generated by Django 3.2.8 on 2021-12-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20211205_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppsettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(max_length=255, null=True)),
                ('whatssap_token', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppsettings', to=settings.AUTH_USER_MODEL, verbose_name='Dht11')),
            ],
        ),
    ]
