# Generated by Django 3.2.8 on 2021-12-05 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_suppsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppsettings',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppsettings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
