# Generated by Django 3.2.8 on 2021-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_fridge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemtry',
            name='max_critical_hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemtry',
            name='max_severe_hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemtry',
            name='min_critical_hum',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='telemtry',
            name='min_severe_hum',
            field=models.FloatField(null=True),
        ),
    ]
