# Generated by Django 3.2.8 on 2021-12-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_dht11_fridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('min_critical_telemetry', models.FloatField(default=None)),
                ('max_severe_telemetry', models.FloatField(default=None)),
                ('max_critical_telemetry', models.FloatField(default=None)),
                ('min_severe_telemetry', models.FloatField(default=None, verbose_name='valeur minimale sévère')),
                ('fridge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='myapp.fridge', verbose_name='Fridge')),
            ],
        ),
        migrations.RemoveField(
            model_name='dht11',
            name='fridge',
        ),
        migrations.DeleteModel(
            name='Telemtry',
        ),
        migrations.AddField(
            model_name='dht11',
            name='asset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dht11s', to='myapp.asset', verbose_name='Asset'),
        ),
    ]
