# Generated by Django 3.2.8 on 2021-12-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211213_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='min_severe_telemetry',
            field=models.FloatField(default=None),
        ),
    ]
